// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CupCss: typeof import('./src/components/cup-css.vue')['default']
    'CupCss copy': typeof import('./src/components/cup-css copy.vue')['default']
    Demo: typeof import('./src/components/demo.vue')['default']
    DemoTpl: typeof import('./src/components/demo-tpl.vue')['default']
    'DemoTpl copy': typeof import('./src/components/demo-tpl copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MVue: typeof import('./src/components/m-vue.vue')['default']
  }
}

export { }
